trigger:
  tags:
    include:
      - '*'
  branches:
    exclude:
      - '*'

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      sudo apt-get update
      sudo apt-get install awscli
      make build-release
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
      AWS_DEFAULT_REGION: eu-west-1
    displayName: 'Deploy public image'